java_library(
    name = "testing",
    testonly = 1,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//javase/java/com/google/time/client/base",
    ],
)
